### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [CompVis/adaptive-style-transfer#14]
Using `python main.py --model_name=my_artist --batch_size=1 --phase=train --image_size=256 --lr=0.0002 --dsr=0.8 --ptcd="E:/data/data_256/" --ptad="E:/style/"` I get

```
Art dataset contains 137 images.
Traceback (most recent call last):
  File "main.py", line 149, in <module>
    tf.app.run()
  File "E:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 132, in main
    model.train(args, ckpt_nmbr=args.ckpt_nmbr)
  File "E:\model.py", line 271, in train
    p.start()
  File "E:\Anaconda\envs\tensorflow\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "E:\Anaconda\envs\tensorflow\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\Anaconda\envs\tensorflow\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "E:\Anaconda\envs\tensorflow\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\Anaconda\envs\tensorflow\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
```
BTW: I am using the smaller image collection with 256 pixel images.

Yet the cursor keeps blinking but the CPU is not being used according to the Task-Manager. Will it continue later, does it need code fixing?

**Comment by asanakoy** [comment]
We havent't tested on Windows. Seems like it is a problem with multiprocessing on Windows.
Try running it on Ubuntu.

**Comment by ErfolgreichCharismatisch** [comment]
It works with ubuntu 18.04. on windows 10 as a subsystem.
