### ISSUE TITLE
How do resolve a problem of the discriminater?

### ISSUE THREAD

**Issue by angleboy8** [CompVis/adaptive-style-transfer#16]
Hi, I find a problem as follows when I test your program. I hope your help. Thank you very much. 

Traceback (most recent call last):
  File "main.py", line 149, in <module>
    tf.app.run()
  File "D:\ProgramData\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 129, in main
    model = Artgan(sess, args)
  File "G:\adaptive-style-transfer-master\model.py", line 68, in __init__
    self._build_model()
  File "G:\adaptive-style-transfer-master\model.py", line 133, in _build_model
    tf.add_n(self.input_photo_discr_loss.values()) + \
  File "D:\ProgramData\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2154, in add_n
    raise ValueError("inputs must be a list of at least one"
ValueError: inputs must be a list of at least oneTensor/IndexedSlices with the same dtype and shape

**Comment by xueqinxiang** [comment]
Hi, angleboy8, please follow this page:https://github.com/CompVis/adaptive-style-transfer/issues/6
