### ISSUE TITLE
failed to train model

### ISSUE THREAD

**Issue by HosseinMM** [CompVis/adaptive-style-transfer#3]
thanks for your great job, I'm running the code and it worked well for style transfer with the models, but when I tried to train on my model, I got this error:
I don't have any experience in coding, I'm just interested in style transfer.
I would be more than happy if you help me on this

____________________________________________________________________________________________
F:\NeuralStyleTransfers\adaptive-style-transfer-master_2\adaptive-style-transfer-master>python main.py --model_name=Farshchiyan_First_Style --batch_size=1 --phase=train --image_size=768 --lr=0.0002 --dsr=0.8 --ptcd=./TrainData/train2014 --ptad=./data/Farshchiyan_first_Style
2018-09-08 13:40:17.233262: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-09-08 13:40:17.630972: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1405] Found device 0 with properties:
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.86
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.61GiB
2018-09-08 13:40:17.837224: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1405] Found device 1 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7845
pciBusID: 0000:02:00.0
totalMemory: 8.00GiB freeMemory: 6.64GiB
2018-09-08 13:40:17.978312: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1405] Found device 2 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7845
pciBusID: 0000:06:00.0
totalMemory: 8.00GiB freeMemory: 6.64GiB
2018-09-08 13:40:17.981198: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1484] Adding visible gpu devices: 0, 1, 2
2018-09-08 13:40:20.650595: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-08 13:40:20.653751: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971]      0 1 2 
2018-09-08 13:40:20.655384: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 0:   N N N 
2018-09-08 13:40:20.657080: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 1:   N N N 
2018-09-08 13:40:20.658863: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 2:   N N N 
2018-09-08 13:40:20.661335: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6372 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-09-08 13:40:20.681136: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 6403 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1070, pci bus id: 0000:02:00.0, compute capability: 6.1)
2018-09-08 13:40:20.699847: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 6403 MB memory) -> physical GPU (device: 2, name: GeForce GTX 1070, pci bus id: 0000:06:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "main.py", line 149, in <module>
    tf.app.run()
  File "C:\Users\rohollah\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 129, in main
    model = Artgan(sess, args)
  File "F:\NeuralStyleTransfers\adaptive-style-transfer-master_2\adaptive-style-transfer-master\model.py", line 68, in __init__
    self._build_model()
  File "F:\NeuralStyleTransfers\adaptive-style-transfer-master_2\adaptive-style-transfer-master\model.py", line 133, in _build_model
    tf.add_n(self.input_photo_discr_loss.values()) + \
  File "C:\Users\rohollah\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2118, in add_n
    raise ValueError("inputs must be a list of at least one Tensor with the "
ValueError: inputs must be a list of at least one Tensor with the same dtype and shape
_____________________________________________________________________________________________

**Comment by asanakoy** [comment]
@dimakot55 please take a look

**Comment by dimakot55** [comment]
Are you using some specific content dataset different to places dataset? Maybe try to specify single Cuda device. Sorry, right now I can't dig into your problem, will take me a few days to look at it. Have you tried to train it on Linux OS?

**Comment by HosseinMM** [comment]
yes, I used train2014.zip that I used to train for the fast style transfer.
I trained it only on windows 10.
do I need to download Places365-Standard high-res ? cause Its hard for me to download that large file size.

**Comment by mnill** [comment]
Make sure you are using tensorflow 1.2

**Comment by asanakoy** [comment]
Closed due to inactivity.
